function randomit(){
    var items = Array(
    "Never have I ever quit drinking more than twice.",
    "Never have I ever peed in a pool.",
    "Never have I ever challenged an animal to a fight.",
    "Never have I ever been kicked out of a bar.",
    "Never have I ever used the bathroom in complete darkness.",
    "Never have I ever been chased by a dog.",
    "Never have I ever worn Crocs.",
    "Never have I ever gotten a tattoo I regret.",
    "Never have I ever called in sick but wasn’t.",
    "Never have I ever kissed an animal.",
    "Never have I ever farted in an elevator and pretended it was not me.",
    "Never have I ever eaten my own bugger.",
    "Never have I ever regifted.",
    "Never have I ever worn a Broken Watch for style.",
    "Never have I ever spent more than $50 on underwear.",
    "Never have I ever used the bathroom in complete darkness.",
    "Never have I ever spilled pen ink in my pocket",
    "Never have I ever tripped and fell in public.",
    "Never have I ever given someone a black eye.",
    "Never have I ever done something I thought I would never do.",
    "Never have I ever stalked someone.",
    "Never have I ever been invited to a threesome.",
    "Never have I ever swam naked in someone else's pool.",
    "Never have I ever gotten drunk playing games like this.",
    "Never have I ever kicked a masseuse during a massage by mistake.",
    "Never have I ever woken up someone with my snoring.",
    "Never have I ever farted while squatting in the gym.",
    "Never have I ever pranked my partner.",
    "Never have I ever tried weed.",
    "Never have I ever driven a car naked.",
    "Never have I ever been trapped in an elevator.",
    "Never have I ever sang at karaoke.",
    "Never have I ever used the 5 second rule for food that fell.",
    "Never have I ever dropped my phone in the toilet.",
    "Never have I ever woken up with bruises and not know how they got there.",
    "Never have I ever kissed a stranger.",
    "Never have I ever not cleaned my teeth for over 48 hrs.",
    "Never have I ever dyed my hair the wrong color!",
    "Never have I ever sang out loud in a friends shower.",
    "Never have I ever been locked in a room.",
    "Never have I ever dropped a phone on my face.",
    "Never have I ever been chased by a cat.",
    "Never have I ever taken a sexy selfie.",
    "Never have I ever sent a dirty text to the wrong person.",
    "Never have I ever had a one night stand.",
    "Never have I ever done it in the sea.",
    "Never have I ever shaved my partner’s pubic hair.",
    "Never have I ever kissed a celebrity.",
    "Never have I ever missed a semicolon.",
    "Never have i ever copied a code from stackoverflow",
    "Never have I ever received a serenade.",
    "Never have I ever got drunk playing never have I ever.",
    "Never have I ever kissed someone of the same gender.",
    "Never have I ever been paid for sex",
    "Never have I ever put a thumb in it.",
    "Never have I ever abandoned my baby mama.",
    "Never have I ever Illegally taken something across the border.",
    "Never have I ever stop remembering my first love",
    "Never have I ever fallen asleep in the cinema.",
    "Never have I ever fought in the street.",
    "Never have I ever tasted myself.",
    "Never have I ever gotten 'head' in a public transport ",
    "Never have I ever used a flavored condom",
    "Never have I ever swam nakd in a pool / beach.",
    "Never have I ever kissed my best friend.",
    "Never have I ever watched a friend (do it).",
    "Never have I ever doubted my heterosexuality.",
    "Never have I been involved in BDSM",
    "Never have I ever cheated.",
    "Never have I ever done it while a family member was in the same room.",
    "Never have I ever touched myself to a Youtube video.",
    "Never have I ever had an open relationship.",
    "Never have I ever been in handcuffs.",
    "Never have I ever role played",
    "Never have I ever had to use lubrication.",
    "Never have I ever had a threesome",
    "Never have I ever had to fake it.",
    "Never have I ever been with the former love of my best friend.",
    "Never have I ever tossed the salad.",
    "Never have I ever fallen in love with anyone that i met on social media.",
    "Never have I ever spied on my neighbours.",
    "Never have I ever experimented to see my sexual orientation.",
    "Never have I ever refused a kiss.",
    "Never have I ever Squirted.",
    "Never have I ever flashed a bartender for a free drink.",
    "Never have I ever done it in a public place.",
    "Never have I ever stalked an ex’s boyfriend or girlfriend on social media.",
    "Never have I ever been in handcuffs, for any reason.",
    "Never have I ever done it on my period.",
    "Never have I ever licked food off someone.",
    "Never have I ever done it on a kitchen counter.",
    "Never have I ever been with someone 10 inches or longer.",
    "Never have I ever showered with the same sex.",
    "Never have I ever slept with twins.",
    "Never have I ever had an orgy.",
    "Never have I ever caught my parents doing it.",
    "Never have I ever been choked.",
    "Never have I ever stalked an ex online.",
    "Never have I ever sucked my partners toes.",
    "Never have I ever screwed around in an elevator.",
    "Never have I ever slept with someone within an hour of meeting them.",
    "Never have I ever had an STD.",
    "Never have I ever given/received a lap dance.",
    "Never have I ever required medical attention due to a foreign object stuck inside my body.",
    "Never have I ever been upset with a partner for not performing well.",
    "Never have I ever used a friends pleasure toys.",
    "Never have I ever sent someone a picture of my stuff.",
    "Never have I ever been upset with a partner for not performing well.",
    "Never have I ever gotten dehydrated during a session.",
    "Never have I ever named a location after a session.",
    "Never have I ever sucked toes.",
    "Never have I ever done it with a family member in the same room (dirty!).",
    "Never have I ever done it With a family member in the same building.",
    "Never have I ever watched another couple get it on.",
    "Never have I ever tasted someone else bodily fluids.",
    "Never have I ever removed clothing in public that was not mine.",
    "Never have I ever been walked in on by my parents.",
    "Never have I ever screwed around in an elevator.",
    "Never have I ever had an relative walk in while I was getting it on.",
    "Never have I ever licked food off someone.",
    "Never have I ever tossed the salad.",
    "Never have I ever slept with someone within an hour of meeting them.",
    "Never have I ever been fooling around in the car and accidentally honked the horn.",
    "Never have I ever taken nude photos of myself/someone else.",
    "Never have I ever done it with someone more than twice my age.",
    "Never have I ever pleasured given my boyfriend/girlfriend for more than half an hour.",
    "Never have I ever shaved my partner’s pubic hair.",
    "Never have I ever lied about my sexuality not to feel out of place",
    "Never have I ever kissed a celebrity.",
    "Never have I ever been to a sex party",
    "Never have I ever debugging codes all night for work",
    "Never have I ever been choked.",
    "Never have I ever purchased a pleasuring toy.",
    "Never have I ever tricked an animal into licking my private.",
    "Never have I ever had a dirty crush on somebody in this circle.",
    "Never have I ever tasted breast milk.",
    "Never have I ever flirted with a friends sibling.",
    "Never have I ever forgot to fill my car with water.",
    "Never have I ever put a thumb in it.",
    "Never have I ever abandoned my baby mama.",
    "Never have I ever been to a gay club.",
    "Never have I ever been on a dating app",
    "Never have I ever passed out from suffocation during…",
    "Never have I ever snuck a girl/guy into the house.",
    "Never have I ever used a sock when I was…",
    "Never have I ever played with a partners body more than my own.",
    "Never have I ever fell asleep watching…you know what.",
    "Never have I ever tasted myself.",
    "Never have I ever watched a friend doing it with their partner.",
    "Never have I ever completed a session without ever laying down.",
    "Never have I ever been accused of being With someone other than my partner.",
    "Never have I ever not washed a piece of clothing because of someone else scent.",
    "Never have I ever had to use lubrication.",
    "Never have I ever used sex toys",
    "Never have I ever tied someone up during sex",
    "Never have I ever cheated.",
    "Never have I ever been dominated.",
    "Never have I ever been upset with A partner for not performing well.",
    "Never have I ever gotten dehydrated during sex.",
    "Never have I ever named a Location After a session.",
    "Never have I ever done it with a family member in the same room.",
    "Never have I ever done it with a family member in The same building.",
    "Never have I ever watched another couple get it on.",
    "Never have I ever removed clothing in public that was not mine.",
    "Never have I ever done it outside.",
    "Never have I ever slept with an older lady",
    "Never have I ever had a *dream* about a professor.",
    "Never have I ever licked food off someone.",
    "Never have I ever flashed someone.",
    "Never have I ever done it in the back of a pickup truck.",
    "Never have I ever slept in a bed with more than five people.",
    "Never have I ever masturbated in a public toilet",
    "Never have I ever done it with someone more than twice my age.",
    "Never have I ever had done it while in the shower.",
    "Never have I ever fooled around in a sibling’s room.",
    "Never have I ever woken up to someone giving me head.",
    "Never have I ever had done it with more than one person within 24 hours.",
    "Never have I ever found myself attracted to my pet.",
    "Never have I ever tried it in the rear.",
    "Never have I ever used sex to get out of a tough situation.",
    "Never have I ever been tied up during sex.",
    "Never have I ever screwed around in an elevator.",
    "Never have I ever slept with a co-worker.",
    "Never have I ever taken nude photos of myself/someone else.",
    "Never have I ever eaten ass.",
    "Never have I ever had my ass eaten out.",
    "Never have I ever done it while at a party.",
    "Never have I ever done it on the toilet (dirty I know).",
    "Never have I ever been fooling around in the car and accidentally honked the horn.",
    "Never have I ever caught my parents doing it.",
    "Never have I ever flashed for a stranger.",
    "Never have I ever had a clingy partner.",
    "Never have I ever had sex with my boss.",
    "Never have I ever sucked on someone’s toes.",
    "Never have I ever done it in front of other people.",
    "Never have I ever left bite marks on someone.",
    "Never have I ever slept with someone I thought was ugly.",
    "Never have I ever done it in a sleeping bag.",
    "Never have I ever tasted something nasty off my partner.",
    "Never have I ever not washed a piece of clothing because of someone else scent.",
    "Never have I ever had to use lubrication.",
    "Never have I ever cheated.",
    "Never have I ever recorded while having sex.",
    "Never have I ever been kicked out of a bar.",
    "Never have I ever thrown up and swallow it.",
    "Never have I ever had sex in public.",
    "Never have I ever Skinny Dipped.",
    "Never have I ever taken the morning after pill.",
    "Never have I ever driven through red lights.",
    "Never have I ever had sex in a toilet.",
    "Never have I ever stalked my Ex.",
    "Never have I ever checked through my phone media to remember the night before.",
    "Never have I ever farted in an elevator and pretended it was not me.",
    "Never have I ever put a thumb in it.",
    "Never have I ever hooked up with more than one person in a single day.",
    "Never have I ever had a sugar daddy.",
    "Never have I ever had sex at work.",
    "Never have I ever went to work without bathing.",
    "Never have I ever created an Instagram just to stalk people.",
    "Never have I ever accepted a drop from total strangers.",
    "Never have I ever eaten raw fish.",
    "Never have I ever tasted myself.",
    "Never have I ever watched a friend (do it).",
    "Never have I ever done it with a family member in the same building.",
    "Never have I ever said I am never drinking again.",
    "Never have I ever made a wish after seeing a falling star.",
    "Never have I ever used Facebook.",
    "Never have I ever been to be the Tooth Fairy.",
    "Never have I ever coughed on my boss.",
    "Never have I ever shot a person by accident.",
    "Never have I ever kissed a celebrity.",
    "Never have I ever used Tiktok.",
    "Never have I ever liked a book to movie adaptation more than the book.",
    "Never have I ever cut my own hair.",
    "Never have I ever been to (2) or more nightclubs in one night.",
    "Never have I ever crushed on a celebrity.",
    "Never have I ever used Twittwer.",
    "Never have I ever pretends to be sleeping",
    "Never have I ever broke my computer",
    "Never have I ever used Telegram.",
    "Never have I ever begged for food.",
    "Never have I ever chased after someone in the street.",
    "Never have I ever smoked any substance.",
    "Never have I ever tried a BuzzFeed recipe.",
    "Never have I ever been chased by a cat.",
    "Never have I ever used Instagram.",
    "Never have I ever cooked outdoors.",
    "Never have I ever slept on the floor.",
    "Never have I ever hosted a barbecue.",
    "Never have I ever done body shots.",
    "Never have I ever slept with my pet.",
    "Never have I ever danced on a bar.",
    "Never have I ever tasted breast milk.",
    "Never have I ever tried bathing in a fountain.",
    "Never have I ever slipped on nothing.",
    "Never have I ever been to the circus.",
    "Never have I ever used an emoji when texting.",
    "Never have I ever built A Snow Man.",
    "Never have I ever lost weight from stress.",
    "Never have I ever been walked in on by someone.",
    "Never have I ever ridden a motorcycle.",
    "Never have I ever walked into a glass window.",
    "Never have I ever been in handcuffs, for any reason.",
    "Never have I ever been locked in a room for more than an hour.",
    "Never have I ever started a fight.",
    "Never have I ever peed in the shower.",
    "Never have I ever voted for Trump.",
    "Never have I ever fell asleep on the bus and missed my stop.",
    "Never have I ever set something on fire (people included).",
    "Never have I ever played beer pong.",
    "Never have I ever held a gun.",
    "Never have I ever had a one night stand.",
    "Never have I ever sniffed marker ink.",
    "Never have I ever pulled a push door.",
    "Never have I ever laughed so hard I peed a little.",
    "Never have I ever gone without a bath or shower for more than a week.",
    "Never have I ever picked at a wedgie in public.",
    "Never have I ever thrown up because someone else threw up.",
    "Never have I ever made a prank phone call.",
    "Never have I ever set something on fire (people included).",
    "Never have I ever tasted cat food.",
    "Never have I ever sharted.",
    "Never have I ever been bungee jumping.",
    "Never have I ever been sneezed on.",
    "Never have I ever gone commando.",
    "Never have I ever slipped and fell on nothing.",
    "Never have I ever had sushi.",
    "Never have I ever shot a person by accident.",
    "Never have I ever used the bathroom in complete darkness.",
    "Never have I ever sent my food back to the chef.",
    "Never have I ever accepted a drop from total strangers.",
    "Never have I ever crushed on a celebrity.",
    "Never have I ever been chased by a dog.",
    "Never have I ever changed a car tire.",
    "Never have I ever done body shots.",
    "Never have I ever won a game of Monopoly.",
    "Never have I ever kissed an animal.",
    "Never have I ever been to the circus.",
    "Never have I ever cheated on a test.",
    "Never have I ever been on TV.",
    "Never have I ever fallen asleep in the cinema.",
    "Never have I ever been to 2 or more nightclubs in one night.",
    "Never have I ever teased an army official.",
    "Never have I ever measured my junk.",
    "Never have I ever done something totally stupid and broke a bone.",
    "Never have I ever driven before I had my license.",
    "Never have I ever tried dancing like Michael Jackson.",
    "Never have I ever messed with the watchman.",
    "Never have I ever set my house on fire.",
    "Never have I ever hit someone for no reason.",
    "Never have I ever frightened someone using the deepness of my voice.",
    "Never have I ever tripped someone in public.",
    "Never have I ever shouted to hear my echo.",
    "Never have I ever farted in a closed space and watched others squeal.",
    "Never have I ever stolen alcohol from the kitchen.",
    "Never have I ever damaged my parent's vehicle and fixed it on the same night.",
    "Never have I ever chased down an animal while driving.",
    "Never have I ever gone commando.",
    "Never have I ever flirted with a much older lady.",
    "Never have I ever been caught 'doing it'.",
    "Never have I ever ran across the road to avoid a car.",
    "Never have I ever fallen asleep on my partner while watching TV.",
    "Never have I ever peed in the shower.",
    "Never have I ever laughed until I threw up.",
    "Never have I ever done an adrenaline junkie activity with my partner like skydiving",
    "Never have I ever used Tinder.",
    "Never have I ever tried speed dating.",
    "Never have I ever dated someone I was told to date by friends.",
    "Never have I ever been stressed by my partner.",
    "Never have I ever done a double date.",
    "Never have I ever dreamed about my wedding day.",
    "Never have I ever eaten only ice cream for a whole day.",
    "Never have I ever tried to change my partner's phone to an iPhone.",
    "Never have I ever tried to impress someone who hates me.",
    "Never have I ever cheated.",
    "Never have I ever traveled with a significant other.",
    "Never have I ever dinned and dashed with a significant other.",
    "Never have I ever thrown up on a friend.",
    "Never have I ever laughed so hard I sharted.",
    "Never have I ever had a picnic date.",
    "Never have I ever played two truths ad a lie with as a conversation starter.",
    "Never have I ever cried in front of the boys",
    "Never have I ever hook up with someone in a bar.",
    "Never have I ever broken up with someone over text.",
    "Never have I ever left a drunk voicemail.",
    "Never have I ever flown first class.",
    "Never have I ever saved someone else’s life.",
    "Never have I ever had a panic attack.",
    "Never have I ever been fired.",
    "Never have I ever watched an entire television series in a day",
    "Never have I ever had a one-night stand and stayed for breakfast.",
    "Never have I ever had to do a walk of shame.",
    "Never have I ever been kicked out of a club.",
    "Never have I ever lied during a job interview.",
    "Never have I ever fallen asleep during sex.",
    "Never have I ever role-played in bed.",
    "Never have I ever gone to a strip club.",
    "Never have I ever done it on a kitchen counter.",
    "Never have I ever slept with identical twins.",
    "Never have I ever slept with a friend’s partner.",
    "Never have I ever swallowed on the very first blowjob.",
    "Never have I ever lied about “my number” to someone that I’m dating.",
    "Never have I ever been in a snow storm.",
    "Never have I ever been handcuffed.",
    "Never have I ever lied to protect a cheating friend.",
    "Never have I ever woken up to someone giving me head.",
    "Never have I ever made out with a friend’s older brother.",
    "Never have I ever donated to a charity.",
    "Never have I ever loved and hated the same person.",
    "Never have I ever gone to an Escape Room.",
    "Never have I ever taken nude pictures of a friend.",
    "Never have I ever skipped out on a restaurant bill.",
    "Never have I ever won the lottery.",
    "Never have I ever had to go to court.",
    "Never have I ever had stitches from an injury.",
    "Never have I ever crashed a wedding.",
    "Never have I ever trolled someone on social media.",
    "Never have I ever climbed out of a window.",
    "Never have I ever laughed so hard that I peed my pants.",
    "Never have I ever tried smoking marijuana.",
    "Never have I ever tried smoking a cigarette.",
    "Never have I ever gotten a tattoo.",
    "Never have I ever done a 10-hour movie marathon in one day.",
    "Never have I ever made up a fake boyfriend/girlfriend.",
    "Never have I ever spent more than $1000 in a video game.",
    "Never have I ever thrown a drink at someone.",
    "Never have I ever worn someone else’s underwear.",
    "Never have I ever tried scuba diving.",
    "Never have I ever done a TikTok dance.",
    "Never have I ever been arrested because I joined a protest.",
    "Never have I ever partied non-stop for more than twenty-four hours.",
    "Never have I ever had a friend with benefits.",
    "Never have I ever went to the movie theater alone.",
    "Never have I ever dropped my pants in public.",
    "Never have I ever had a surprise party thrown for me.",
    "Never have I ever tried a dating app.",
    "Never have I ever went to Disney World.",
    "Never have I ever impulse bought a ridiculous item while drunk.",
    "Never have I ever had a crush on Justin Bieber!",
    "Never have I ever not showered for more than a week.",
    "Never have I ever botched a job interview.",
    "Never have I ever been involve in car race.",
    "Never have I ever change a tire.",
    "Never have I ever Secretly watched a ahead in a TV show after promising a friend or partner you would watch together.",
    "Never have I ever work for more then 12 hours straight.",
    "Never have I ever been retweeted or followed by a celebrity.",
    "Never have I ever accidentally texted somthing embarrasing to the wrong person.",
    "Never have I ever surf in the ocean",
    "Never have I ever ordered delivery from a restaurant that was less than 1 kilometer away.",
    "Never have I ever had a medical emergency at work.",
    "Never have I ever ride on a motorcycle.",
    "Never have I ever designed an app.",
    "Never have I ever took a magic mushroom",
    "Never have I ever been attacked by a wild animal.",
    "Never have I ever brewed my own beer.",
    "Never have I ever written and recorded a song.",
    "Never have I ever stolen someone else's story and passed it off as my own.",
    "Never have I ever played video games for 10+ hours a day.",
    "Never have I ever dance to the song, 'Baby' by Justin Bieber.",
    "Never have I ever eaten out 3 or more times in one day.",
    "Never have I ever kill an animal(humans count).",
    "Never have I ever read a full book in one day.",
    "Never have I ever seen one of the 7 wonders of the world i person.",
    "Never have I ever scream during an intercurse.",
    "Never have I ever been involve in a car accident.",
    "Never have I ever ran a website.",
    "Never have I ever Masturbated at work",
    "Never have I ever had sex with a customer at work",
    "Never have I ever been to South America.",
    "Never have I ever been skydiving.",
    "Never have I ever been to Africa.",
    "Never have I ever been to an island",
    "Never have I ever been to Japan.",
    "Never have I ever been to Europe.",
    "Never have I ever been to China.",
    "Never have I ever been to Mongolia.",
    "Never have I ever been to India.",
    "Never have I ever gone skiing.",
    "Never have I ever been to the country of my heritage.",
    "Never have I ever ridden on an elephant",
    "Never have I ever been on a cruise.",
    "Never have I ever flown in a helicopter.",
    "Never have I ever been ice skatting",
    "Never have I ever have you ever been to the circus?",
    "Never have I ever been involved in criminal activities.",
    "Never have I ever driven drunk.",
    "Never have I ever gone on a road trip with my friends.",
    "Never have I ever done ecstasy",
    "Never have I ever blown a line of cocaine off of someone's body.",
    "Never have I ever done cocaine",
    "Never have I ever run from a polic officer",
    "Never have I ever ate brownies with weed in them.",
    "Never have I ever thought about what type of dog I would be.",
    "Never have I ever lied about my income.",
    "Never have I ever blacked out from drinking.",
    "Never have I ever had to call the cops on someone.",
    "Never have I ever eaten my colleague’s snacks.",
    "Never have I ever ridden a mechanical bull.",
    "Never have I ever been to the emergency room because of alcohol/drugs.",
    "Never have I ever committed a felony.",
    "Never have I ever had braces.",
    "Never have I ever given money to a homeless person.",
    "Never have I ever lied about what I do for a living.",
    "Never have I ever met an internet friend in real life.",
    "Never have I ever forgotten my phone in a cab.",
    "Never have I ever designed a video game.",
    "Never have I ever participated in an internet challenge.",
    "Never have I ever met my doppleganger.",
    "Never have I ever Solved a 1,000+ piece jigsaw puzzle.",
    "Never have I ever Cried when a fictional character died.",
    "Never have I ever pretended to have an accent.",
    "Never have I ever seen 2 of the 7 wonders of the world i person.",
    "Never have I ever started a social media account for a pet.",
    "Never have I ever ridden a horse",
    "Never have I ever gotten pickpocketed.",
    "Never have I ever bought unnecessary items, just for the discount.",
    "Never have I ever tried hard drugs.",
    "Never have I ever played strip poker.",
    "Never have I ever driven without a license.",
    "Never have I ever been mugged.",
    "Never have I ever felt an earthquake.",
    "Never have I ever given a pet for adoption.",
    "Never have I ever marched in a protest.",
    "Never have I ever read a partner text messenger.",
    "Never have I ever lied about who i voted for.",
    "Never have I ever dated or hooked up with someone 10 years older.",
    "Never have I ever flirt with a married person.",
    "Never have I ever got lost in a foreign city, without speaking the local language.",
    "Never have I ever lied during this game!.",
    "Never have I ever been robbed.",
    "Never have I ever spent a night in jail.",
    "Never have I ever hooked up with a friend's ex.",
    "Never have I ever ghosted a partner completely.",
    "Never have I ever been in a sand storm.",
    "Never have I ever cried during a movie.",
    "Never have I ever mixed white and colored clothes while doing laundry.",
    "Never have I ever ran out of gas in the middle of the road.",
    "Never have I ever broken someone’s nose.",
    "Never have I ever been slapped in the face.",
    "Never have I ever seen a lunar eclipse.",
    "Never have I ever caused a big loss for the company I work for.",
    "Never have I ever created a false account on social media.",
    "Never have I ever caused a fight.",
    "Never have I ever regretted a tattoo shortly after doing it.",
    "Never have I ever played paintball.",
    "Never have I ever sneaked into a party I wasn’t invited to.",
    "Never have I ever broken a bone in my body.",
    "Never have I ever got COVID-19.",
    "Never have I ever found money on the street, and kept it.",
    "Never have I ever gone to cinema alone.",
    "Never have I ever collected a set of Yu-Gi-Oh! cards.",
    "Never have I ever got a tattoo I’ve never told anyone about.",
    "Never have I ever walked barefoot on the streets.",
    "Never have I ever kissed someone under the rain.",
    "Never have I ever had more than 3 pets at any given time.",
    "Never have I ever jumped in the pool fully dressed.",
    "Never have I ever spilled wine on expensive furniture at someone’s house.",
    "Never have I ever had more than one partner at a time.",
    "Never have I ever collected a set of Pokémon cards.",
    "Never have I ever caused a fire.",
    "Never have I ever been in a limousine.",
    "Never have I ever accidentally killed a pet.",
    "Never have I ever ran over an animal while driving.",
    "Never have I ever worked freelance jobs.",
    "Never have I ever visited more than 5 countries.",
    "Never have I ever noticed I’ve been lied to, but acted as if I didn’t.",
    "Never have I ever had two separate cellphone numbers, for different purposes.",
    "Never have I ever accepted help from a complete stranger.",
    "Never have I ever gone to a concert alone.",
    "Never have I ever got a piercing.",
    "Never have I ever been in a car accident.",
    "Never have I ever vomited in public.",
    "Never have I ever been kidnapped.",
    "Never have I ever been on a flight for more than 12 hours.",
    "Never have I ever had an animal chase after me.",
    "Never have I ever booked a fancy hotel suite.",
    "Never have I ever sold used items online.",
    "Never have I ever paid a gym subscription without actually using it.",
    "Never have I ever been cheated on more than once by the same partner.",
    "Never have I ever been trapped in an elevator for more than an hour.",
    "Never have I ever pretended to be someone’s friend to help them out of an awkward or dangerous situation.",
    "Never have I ever bought gym equipment for home, but never used it.",
    "Never have I ever seen a building collapse.",
    "Never have I ever been in an ambulance.",
    "Never have I ever fell asleep during a class.",
    "Never have I ever participated in a food eating contest.",
    "Never have I ever cheated on an exam.",
    "Never have I ever spoken to a celebrity.",
    "Never have I ever thought of hurting myself.",
    "Never have I ever catfished someone.",
    "Never have I ever seen a car accident happen in front of me.",
    "Never have I ever fallen asleep while taking public transportation.",
    "Never have I ever dropped out of a university class.",
    "Never have I ever eaten food off of someone’s body.",
    "Never have I ever completely change university majors halfway through.",
    "Never have I ever fell asleep in the shower.",
    "Never have I ever slept in an airport.",
    "Never have I ever gone to a place just for the sake of taking a specific photo or video for social media.",
    "Never have I ever witnessed a tornado.",
    "Never have I ever attended a video call for work from an unexpected location.",
    "Never have I ever been ghosted by someone I really liked.",
    "Never have I ever been football (soccer) World Cup match.",
    "Never have I ever lived (not visited) in more than 3 countries.",
    "Never have I ever spent my birthday alone.",
    "Never have I ever sneaked into the cinema without a ticket.",
    "Never have I ever eaten snow.",
    "Never have I ever cried in public",
    "Never have I ever been catfished by someone.",
    "Never have I ever watched the same movie twice in one day.",
    "Never have I ever burned through my savings account.",
    "Never have I ever gone fishing.",
    "Never have I ever learned to play a musical instrument.",
    "Never have I ever been put in the friendzone.",
    "Never have I ever helped a complete stranger.",
    "Never have I ever been featured on the news.",
    "Never have I ever won a scholarship.",
    "Never have I ever hit a friend in the face.",
    "Never have I ever taught a class",
    "Never have I ever refused to accept a gift.",
    "Never have I ever fell asleep during a date.",
    "Never have I ever walked in on someone in a public bathroom.",
    "Never have I ever been to a str!p club.",
    "Never have I ever seen a dead body.",
    "Never have I ever taken pictures of meals before eating.",
    "Never have I ever pretended to be someone I’m not.",
    "Never have I ever given someone a black eye.",
    "Never have I ever looked through someone’s phone without their permission.",
    "Never have I ever shot a gun.",
    "Never have I ever gave a wrong name to my branch.",
    "Never have I ever performed on stage.",
    "Never have I ever been on a double date",
    "Never have I ever changed a local commits before a push.",
    "Never have I ever pushed a wrong branch to the remote.",
    "Never have I ever dyed my hair.",
    "Never have I ever played 'Never Have I Ever'.",
    "Never have I ever ditched out on paying the bill at a restaurant.",
    "Never have I ever eaten food from the garbage.",
    "Never have I ever went to the hospital for something embarrassing.",
    "Never have I ever got bitten by a snake.",
    "Never have I ever forgot to add changes to the last commit.",
    "Never have I ever tried cutting my own hair.",
    "Never have I ever added a file I didn't want in the repo.",
    "Never have I ever committed all changes to the master branch.",
    "Never have I ever wished to be single again.",
    "Never have I ever done it in a sleeping bag.",
    "Never have I ever lied to get out of going to work.",
    "Never have I ever picked up a hitchhiker.",
    "Never have I ever got into a physical fight with a good friend.",
    "Never have I ever had a crush on a best friend’s sibling.",
    "Never have I ever pretended I had a phone call to get out of talking with someone.",
    "Never have I ever made money from performing on the streets.",
    "Never have I ever ate a whole carton of ice cream in one sitting by myself.",
    "Never have I ever taken the blame for something I’ve never done.",
    "Never have I ever had a friends with benefits.",
    "Never have I ever re-gifted a gift. ",
    "Never have I ever had a speeding ticket.",
    "Never have I ever dined and dashed.",
    "Never have I ever DMed a celebrity.",
    "Never have I ever dropped my phone in a toilet.",
    "Never have I ever Googled my own name.",
    "Never have I ever created a fake Instagram account.",
    "Never have I ever broken production.",
    "Never have I ever merged without waiting for tests to pass.",
    "Never have I ever rewritten my code so they circumvent the tests.",
    "Never have I ever commited without testing.",
    "Never have I ever flashed a bartender for a free drink.",
    "Never have I ever closed a ticket without completely finishing everything because the last requirement was unlikely to see the light of day.",
    "Never have I ever left an unfinished project on my GitHub.",
    "Never have I ever used a Jetbrains product for more than a week.",
    "Never have I ever committed a secret by accident.",
    "Never have I ever written C++.",
    "Never have I ever written C.",
    "Never have I ever written C#.",
    "Never have I ever written Perl.",
    "Never have I ever written Python.",
    "Never have I ever written Java.",
    "Never have I ever written Pascal.",
    "Never have I ever written Go.",
    "Never have I ever written SQL.",
    "Never have I ever written PHP.",
    "Never have I ever written code in Ruby.",
    "Never have I ever written code in R.",
    "Never have I ever wrote a SQL query.",
    "Never have I ever squashed commits to hide the fact that I introduced the major bug I'm now fixing...",
    "Never have I ever wrote a tutorial post.",
    "Never have I ever used AWS.",
    "Never have I ever used Firebase.",
    "Never have I ever used Unity engine.",
    "Never have I ever used Unreal engine.",
    "Never have I used Vim or Emacs.",
    "Never have I ever rm -rf / prod server.",
    "Never have i ever write a spaghetti code.",
    "Never have I ever written perfect code.",
    "Never have I ever used Linux.",
    "Never have I ever subscribe to a movie streaming product.",
    "Never have I ever been invited to Hogwarts.",
    "Never have I ever knock some one out.",
    "Never have I ever been under general anesthetic.",
    "Never have I ever have had flowers delivered to me.",
    "Never have I ever had sex outdoors.",
    "Never have I bought clothing item for more than 500$.",
    "Never have I ever ate sea food.",
    "Never have I ever ate a pork.",
    "Never have I ever bought a car.",
    "Never have I ever drive a car."

    
    );




    // var t = console.log(items.length);

    var item = items[Math.round(Math.random()*items.length)];
  
    // document.write('<p id="question">'+item+'</p>');
    
    return item;
}

const nvr = randomit();
    document.querySelector('.button').addEventListener('click', function () { 
    document.querySelector('.init').innerText = randomit();
    
})


